[package]
name = "vellum-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "vellum-gui"
path = "src/main.rs"

[dependencies]
vellum-app = { path = "../vellum-app" }
# TODO: Floem
