
[keyboard]
# These are the default keybinds. They can be overridden by the user in a config file.
"Up" = "ShiftCursorUp"
"Down" = "ShiftCursorDown"
"Left" = "ShiftCursorLeft"
"Right" = "ShiftCursorRight"
"Home" = "ShiftCursorLineStart"
"End" = "ShiftCursorLineEnd"
"PageUp" = "ShiftCursorDocStart"
"PageDown" = "ShiftCursorDocEnd"
"Ctrl+Left" = "ShiftCursorTokenLeft"
"Ctrl+Right" = "ShiftCursorTokenRight"
"Ctrl+q" = "Exit"
"Ctrl+o" = "Open"
"Ctrl+s" = "Save"
"Ctrl+C" = "Close"
"Ctrl+c" = "Copy"
"Ctrl+v" = "Paste"
"Ctrl+x" = "Cut"
"Ctrl+z" = "Undo"
"Ctrl+y" = "Redo"
"Delete" = "Delete"
"Ctrl+Delete" = "DeleteLine"
"Insert" = "Insert"
"Ctrl+a" = "SelectAll"
"Ctrl+b" = "Bold"
"Ctrl+i" = "Italic"
"Ctrl+u" = "Underline"